# Environmental Drivers

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(ggplot2) 
library(dplyr) 
library(lubridate) 
library(viridis)
library(sharpshootR)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
theme_plots <- theme_bw() + theme(axis.text = element_text(size = 12),
                                  strip.text = element_text(size = 12),
                                  legend.text = element_text(size = 12),
                                  axis.title = element_text(size = 13),
                                  axis.title.x = element_blank(),
                                  legend.title = element_blank(),
                                  legend.position = "top",
                                  axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))
```

## Water Quality {#wq}

Flows at Keswick were lower in 2022 (Figure \@ref(fig:KWKflow-fig)).

```{r KWKflow-fig, echo=FALSE, message=FALSE, warning=FALSE, fig.cap = "Flows at Keswick (KWK), 2019-2022."}
flow_kwk <- readRDS("data_raw/USGS_NWIS_11370500_flow.rds") %>%
  filter(year>2018 & year<2023) %>%
  group_by(year, fyear, date, date2) %>%
  summarize(flow = mean(flow_inst, na.rm = TRUE)) %>%
  ungroup()

ggplot(flow_kwk) + geom_line(aes(date2, flow, color = fyear)) +
  scale_color_viridis(discrete = TRUE, option = "turbo") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d") +
  labs(y = "Flow (cfs)") +
  theme_plots +
  theme(legend.title = element_blank())
```


```{r DOTurb-fig, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Dissolved Oxygen and Turbidity at Keswick Dam (KWK) and Sacramento River upstream from Confluence with Clear Creek (CCR)."}

do_data <- readRDS("data_raw/do_cdec_2017-2023.rdsxz")
turb_data <- readRDS("data_raw/turbidity_cdec_2017-2023.rdsxz")
do_turb_data <- left_join(do_data, turb_data %>% dplyr::select(datetime, station, Turbidity))
do_turb_long <- do_turb_data %>% tidyr::pivot_longer(cols = c(DO, Turbidity),
                                                     names_to = "parameter",
                                                     values_to = "value")
do_turb_recent <- do_turb_long %>%
  filter(year==2021) %>%
  group_by(wy, year, month, date, date2, station, parameter) %>%
  summarize(value = mean(value, na.rm = TRUE))

ggplot(do_turb_recent) + geom_line(aes(date, value, color = station)) +
  facet_wrap(~parameter, scales = "free_y", nrow = 2,
             labeller = as_labeller(c(DO = "Dissolved Oxygen\n(mg/L)", Turbidity = "Turbidity (NTU)")),
             strip.position = "left") + 
  scale_color_manual(values = c("#E69F00", "#0072B2")) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d") +
  theme_plots +
  theme(axis.title.y = element_blank())
  
```

```{r BSFwtemp-fig, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Sacramento River Water Temperature at Ball's Ferry Bridge TCP (BSF)."}
temp_data <- readRDS("data_raw/temp_cdec_2011-2023.rdsxz")
temp_BSF <- temp_data %>%
  filter(station == "BSF",
         year == 2021,
         month>3 & month < 10) %>%
  group_by(date) %>%
  summarize(Temperature = mean(Temperature, na.rm = TRUE))

ggplot(temp_BSF) + 
  geom_line(aes(date, Temperature), color = "steelblue") +
  geom_hline(yintercept  = 56, linetype = "dashed", color = "gray50") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d") +
  labs(y = "Water Temperature (°C)") +
  theme_plots 

```

 Water temperatures were warmer than average in 2020 (Figure \@ref(fig:historicalwtemp-fig)).
 
```{r historicalwtemp-fig, echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Historical Comparison of Sacramento River Water Temperature at Clear Creek (CCR) and Balls Ferry Bridge (BSF)."}
temp_years <- temp_data %>%
  filter(date<as.Date("2022-01-01")) %>%
  group_by(date, date2, year, month, wy, station) %>%
  summarize(Temperature = mean(Temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(fyear = factor(year)) %>%
  dplyr::select(station, date2, Temperature, fyear)

temp_avg <- temp_data %>%
  filter(date<as.Date("2022-01-01")) %>%
  group_by(station, date2) %>%
  summarize(Temperature = mean(Temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(fyear = "mean")

temp_all <- rbind(temp_years, temp_avg) %>%
  filter(fyear %in% c("mean", "2011", "2020", "2017")) %>%
  rename(doy = date2)

ggplot(temp_all) + geom_line(aes(doy, Temperature, color = fyear)) +
  facet_wrap(~station, nrow = 2) + 
  scale_color_viridis(option = "turbo", discrete = TRUE) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d") +
  labs(y = "Water Temperature (°C)") +
  theme_plots 
```




## Habitat

Weir Overtopping


WUA 

